=== magento1211/project-build-magento2/etc/adyen_payment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */
-->
<xs:schema elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="payment">
        <xs:annotation>
            <xs:documentation>
                The root node for payment configuration
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="adyen_credit_cards" type="adyen_credit_cardsType" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="adyen_credit_cardsType">
        <xs:annotation>
            <xs:documentation>
                The containing node for a list of credit card types.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="type" type="AdyenTypeType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AdyenTypeType">
        <xs:annotation>
            <xs:documentation>
                The definition of a credit card type.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="label" type="xs:string" />
            <xs:element name="code_alt" type="xs:string" />
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="order" type="xs:integer" use="required" />
    </xs:complexType>
</xs:schema>

=== magento1211/project-build-magento2/etc/adyen_payment.xml
<?xml version="1.0"?>
<!--
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */
-->
<payment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Adyen_Payment:etc/adyen_payment.xsd">
    <adyen_credit_cards>
        <type id="AE" order="0">
            <label>American Express</label>
            <code_alt>amex</code_alt>
        </type>
        <type id="VI" order="10">
            <label>Visa</label>
            <code_alt>visa</code_alt>
        </type>
        <type id="MC" order="20">
            <label>MasterCard</label>
            <code_alt>mc</code_alt>
        </type>
        <type id="DI" order="30">
            <label>Discover</label>
            <code_alt>discover</code_alt>
        </type>
        <type id="SM" order="40">
            <label>Maestro/Switch</label>
            <code_alt>maestro</code_alt>
        </type>
        <type id="JCB" order="50">
            <label>JCB</label>
            <code_alt>jcb</code_alt>
        </type>
        <type id="DN" order="60">
            <label>Diners</label>
            <code_alt>diners</code_alt>
        </type>
        <type id="MI" order="70">
            <label>Maestro</label>
            <code_alt>maestro</code_alt>
        </type>
        <type id="UN" order="80">
            <label>UnionPay</label>
            <code_alt>cup</code_alt>
        </type>
        <type id="BCMC" order="90">
            <label>Bancontact</label>
            <code_alt>bcmc</code_alt>
        </type>
        <type id="HIPERCARD" order="100">
            <label>Hipercard</label>
            <code_alt>hipercard</code_alt>
        </type>
        <type id="ELO" order="110">
            <label>Elo</label>
            <code_alt>elo</code_alt>
        </type>
        <type id="TROY" order="120">
            <label>Troy</label>
            <code_alt>troy</code_alt>
        </type>
        <type id="DANKORT" order="130">
            <label>Dankort</label>
            <code_alt>dankort</code_alt>
        </type>
    </adyen_credit_cards>
</payment>
